require "spec/rake/spectask"

Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'spec'
  # system("screwdriver spec/javascript/suite.html --browser Safari")
end

task :headless do
  base_dir = "spec/vendor"
  system "rlwrap java -jar #{File.join(base_dir, 'js.jar')} -w -debug #{File.join(base_dir, 'rhino', 'runner.js')}"  
end

# task :default => :spec
