require "spec/rake/spectask"

task :default => "spec:javascript"
  
desc "Run the JavaScript tests (in Safari)"
task "spec:javascript" do
  sh("screwdriver spec/javascript/suite.html --browser Safari")
end

desc "Run the JavaScript tests (in Rhino)"
task "spec:javascript:headless" do
  base_dir = "spec/vendor"
  sh "java -jar #{File.join(base_dir, 'js.jar')} -w -debug #{File.join(base_dir, 'rhino', 'runner.js')}"  
end

desc "Run the Watir tests (in Safari)"
Spec::Rake::SpecTask.new("spec:watir") do |spec|
  spec.libs << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end
