require "spec/rake/spectask"

Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'spec'
  sh("screwdriver spec/javascript/suite.html --browser Safari")
end

task :headless do
  sh "rlwrap java -jar #{File.join(base_dir, 'lib', 'ext', 'js.jar')} -w -debug #{File.join(base_dir, 'js', 'rhino', 'runner.js')}"  
end

task :default => :spec
